Update Daskhub Dockerfile to solve package version errors in Filmdrop Analytics. (#153)
* Update Dockerfile

This change proposes a new build for Daskhub to enable analytics to be functional in Filmdrop due to package version errors between numpy and pangeo. 

Error:
ValueError                                Traceback (most recent call last)
Cell In[2], line 9
      5 logger.setLevel(logging.INFO)
      7 # ItemMap class for display on a slippy map
----> 9 import folium
...
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

What was happening?
pangeo/pangeo-notebook:2022.12.18 already contains a Conda stack with a NumPy that was built back in 2022 (NumPy 1.23.x → C-API “size = 88”).

So, when we did pip install without version locking, the dependencies of the packages compiled a newer version of NumPy that mismatches with the NumPy in pangeo-notebook:2022, which caused a C-ABI mismatch.

The fix: Updated daskhub to use one of the newer pangeo-notebook tags 2025.06.02 

Installed other dependencies needed for testing and running playbooks in analytics.

* patch fix for deleteing analytics when deploy_analytics=false

* Setup proper version locking for daskhub package dependencies

* Added the change entry to Changelog